w4d2/ninety9cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rentals
  post '/cat_rentals/:id/approve' => "cat_rentals#approve", as: "approve"
  post '/cat_rentals/:id/deny' => "cat_rentals#deny", as: "deny"
end

w4d2/ninety9cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date
#  color       :string
#  name        :string
#  sex         :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ActiveRecord::Base
  COLORS = ['gray', 'orange', 'black', 'white']
  SEXES = ['M', 'F']

  validates :name, :birth_date, presence: true
  validates :color, inclusion: COLORS
  validates :sex, inclusion: SEXES

  has_many :cat_rental_requests, dependent: :destroy

  def age
    (Date.today - birth_date).to_i / 365
  end
end

w4d2/ninety9cats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :status, inclusion: ["PENDING", "APPROVED", "DENIED"]
  validates :cat_id, :start_date, :end_date, presence: true
  validate :no_overlapping_approved_requests?

  belongs_to :cat

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def approve!
    ActiveRecord::Base.transaction do
      overlapping_requests.each { |r| r.deny! }
      self.status = "APPROVED"
      self.save!
    end
  end

  def overlapping_requests
    overlapping = []

    self.class.all.each do |r|
      next unless r.cat_id == self.cat_id
      if (self.start_date..self.end_date).cover?(r.start_date) ||
         (self.start_date..self.end_date).cover?(r.end_date) ||
         (self.start_date > r.start_date && self.end_date < r.end_date)
        overlapping << r
      end
    end

    overlapping
  end

  def overlapping_approved_requests
    overlapping_requests.select { |r| r.status == 'APPROVED' }
  end

  def no_overlapping_approved_requests?
    unless overlapping_approved_requests.empty?
      errors.add(:new_request, "can't overlap with approved request")
    end
  end
end

w4d2/ninety9cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

w4d2/ninety9cats/app/controllers/cat_rentals_controller.rb
class CatRentalsController < ApplicationController

  def new
    @cat_rental = CatRentalRequest.new
  end

  def create
    @cat_rental = CatRentalRequest.new(cat_rental_request_params)
    if @cat_rental.save
      redirect_to("/cat_rentals")
    else
      flash[:error] = @cat_rental.errors.full_messages
      render :new
    end
  end

  def show
    @cat_rental = CatRentalRequest.find(params[:id])
  end

  def index
    @cat_rentals = CatRentalRequest.all
  end

  def approve
    @cat_rental = CatRentalRequest.find(params[:id])
    @cat_rental.approve!
    redirect_to cat_url(Cat.find(@cat_rental.cat_id))
  end

  def deny
    @cat_rental = CatRentalRequest.find(params[:id])
    @cat_rental.deny!
    redirect_to cat_url(Cat.find(@cat_rental.cat_id))
  end

  private

  def cat_rental_request_params
    params.require(:cat_rental).permit(:cat_id, :start_date, :end_date)
  end

end

w4d2/ninety9cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to(cat_url(@cat))
    else
      render :new
    end
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end
end

w4d2/ninety9cats/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d2/ninety9cats/app/helpers/cat_rental_helper.rb
module CatRentalHelper
end

w4d2/ninety9cats/app/helpers/cats_helper.rb
module CatsHelper
end

w4d2/ninety9cats/app/views/cat_rental/new.html.erb
<h1>New Cat Rental Request</h1>

<form action= "<%= action_path %>" method="post">
  <input name="_method" value="<%= meth %>" hidden>

  <label>Cat Selection</label>
  <select name="cat_rental[cat_id]">
    <option selected>
    <% Cat.all.each do |cat| %>
    <option value="<%= cat.id  %>" <%= @cat_rental.cat_id == cat.id ? 'selected' : '' %>>
      <%= cat.name.capitalize %>
    </option>
    <% end %>
  </select>
  <br>

  <label for="start_date">start_date</label>
  <input name="cat_rental[start_date]" id="start_date" type="date"
         value="<%= @cat_rental.start_date || '' %>">
  <br>

  <label for="end_date">end_date</label>
  <input name="cat_rental[end_date]" id="end_date" type="date"
         value="<%= @cat_rental.end_date || '' %>">
  <br>

</form>

w4d2/ninety9cats/app/views/cat_rentals/index.html.erb
<h1>Rentals</h1>

  <% attrs = [:cat_id, :start_date, :end_date, :status] %>
  <table>
    <tr>
      <% attrs.each do |thing| %>
        <td><b><%= thing.to_s.capitalize %></b></td>
      <% end %>
    </tr>
    <% @cat_rentals.each do |rental| %>
      <tr>
        <% attrs.each do |thing| %>
          <td><%= rental.send(thing) %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <%= link_to "create", :new_cat_rental %>

w4d2/ninety9cats/app/views/cat_rentals/new.html.erb
<% if flash[:error] %>
  <%= flash[:error] %>
  <%  flash[:error] = nil %>
<% end %>


<h1>New Cat Rental Request</h1>

<form action= "/cat_rentals" method="post">

  <label>Cat Selection</label>
  <select name="cat_rental[cat_id]">
    <option selected>
    <% Cat.all.each do |cat| %>
      <option value="<%= cat.id  %>" <%= @cat_rental.cat_id == cat.id ? 'selected' : '' %>>
        <%= cat.name.capitalize %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="start_date">start_date</label>
  <input name="cat_rental[start_date]" id="start_date" type="date"
         value="<%= @cat_rental.start_date || '' %>">
  <br>

  <label for="end_date">end_date</label>
  <input name="cat_rental[end_date]" id="end_date" type="date"
         value="<%= @cat_rental.end_date || '' %>">
  <br>

  <input type="submit" value="submit">

</form>

w4d2/ninety9cats/app/views/cats/_edit.html.erb
<% action_path = @cat.persisted? ? cat_url(@cat) : '/cats' %>
<% meth = @cat.persisted? ? 'PATCH' : 'POST' %>

<form action= "<%= action_path %>" method="post">
  <input name="_method" value="<%= meth %>" hidden>

  <label for="cat_name">Name</label>
  <input name="cat[name]" id ="cat_name" type="text"
         value="<%= @cat.name || '' %>">
  <br>

  <label for="birth_date">Birthdate</label>
  <input name="cat[birth_date]" id="birth_date" type="date"
         value="<%= @cat.birth_date || '' %>">
  <br>

  <label for="cat_sex_m">Male</label>
  <input name="cat[sex]" id = "cat_sex_m" type="radio" value="M"
         <%= @cat.sex == 'M' ? 'checked' : '' %>>
  <label for="cat_sex_f">Female</label>
  <input name="cat[sex]" id = "cat_sex_f" type="radio" value="F"
         <%= @cat.sex == 'F' ? 'checked' : '' %>>
  <br>

  <label>Color</label>
  <select name="cat[color]">
    <option selected>
    <% Cat::COLORS.each do |color| %>
      <option value="<%= color %>" <%= @cat.color == color ? 'selected' : '' %>>
        <%= color.capitalize %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="description">Description</label>
  <br>
  <textarea name="cat[description]" id="description"><%= @cat.description || '' %></textarea>
  <br>

  <input type="submit" value="submit">
</form>

w4d2/ninety9cats/app/views/cats/edit.html.erb
<h1>Edit a Cat</h1>

<%= render "edit" %>

w4d2/ninety9cats/app/views/cats/index.html.erb
<h1>Index of Cats</h1>

  <% attrs = [:name, :age, :color, :sex] %>
  <table>
    <tr>
      <% attrs.each do |thing| %>
        <td><b><%= thing.to_s.capitalize %></b></td>
      <% end %>
    </tr>
    <% @cats.each do |cat| %>
      <tr>
        <% attrs.each do |thing| %>
          <% if thing == :name %>
            <td><%= link_to cat.send(thing), cat_url(cat) %></td>
          <% else %>
            <td><%= cat.send(thing) %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>

w4d2/ninety9cats/app/views/cats/new.html.erb
<h1>Create a new Cat</h1>

<%= render "edit" %>

w4d2/ninety9cats/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<p><%= @cat.age %> years old, <%= @cat.color %>, <%= @cat.sex %> cat.</p>
<p><%= @cat.description %></p>

<p>
  <li>
    <% @cat.cat_rental_requests.each do |r| %>
      <% next if r.status != "PENDING" %>
      <ul>
        From: <%= r.start_date %>, to: <%= r.end_date %>
        <form method='post' action="<%= approve_url(r)%>">
          <input value = 'Approve' type='submit'>
        </form>
        <form method='post' action="<%= deny_url(r) %>">
          <input value = 'Deny' type='submit'>
        </form>
      </ul>
    <% end %>
  </li>
</p>