w4d4/musicapp/config/routes.rb
Rails.application.routes.draw do
  get 'artists/index'

  root to: "artists#index"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :artists do 
    resources :albums, only: :new
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end
  resources :tracks, except: [:index, :new] do
    resources :notes, only: :create
  end
  resource :notes, only: :destroy
end

w4d4/musicapp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  artist_id  :integer          not null
#  name       :string           not null
#  live       :boolean          default("f"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  validates :artist_id, :name, presence: true
  validates :live, inclusion: [true, false]

  belongs_to :artist
  has_many :tracks, dependent: :destroy
end

w4d4/musicapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :redirect_unless_logged_in

  def show
    find_album!
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @album = Album.new
  end

  def create
    temp_params = album_params
    temp_params[:live] = temp_params[:live] == "true"
    @artist = Artist.find(params[:artist_id])

    @album = @artist.albums.new(temp_params)
    if @album.save
      inform("album \"#{@album.name}\" created")
      redirect_to artist_url(@artist)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    find_album!
  end

  def update
    find_album!
    if @album.update(album_params)
      inform("album \"#{@album.name}\" updated")
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    find_album!
    @artist = @album.artist
    inform("album \"#{@album.name}\" deleted")
    @album.destroy
    redirect_to artist_url(@artist)
  end

  private

  def album_params
    params.require(:album).permit(:name, :live)
  end

  def find_album!
    @album = Album.find(params[:id])
  end
end

w4d4/musicapp/app/helpers/albums_helper.rb
module AlbumsHelper
end

w4d4/musicapp/app/views/albums/_album_form.html.erb
<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token %>">

<label for="name">Name:</label>
<input type="text" name="album[name]" value="<%= @album.name %>" id="name">

<input type="radio" value="false" name="album[live]"
	<%= @album.live ? '' : 'checked' %>>
	Studio
</input>
<input type="radio" value="true" name="album[live]"
	<%= @album.live ? 'checked' : '' %>>
	Live
</input>

<input type="hidden" name="artist_id" value="<%= @artist ? @artist.id : '' %>">
<br>

<%= link_to "cancel", artist_url(@artist) if @artist %>

w4d4/musicapp/app/views/albums/edit.html.erb
<h2>Edit Album</h2>

<form action="<%= album_url(@album) %>" method="post" accept-charset="utf-8">
	<input type="hidden" name="_method" value="patch">
	<%= render "album_form" %>
	<input type="submit" value="edit">
</form>

w4d4/musicapp/app/views/albums/new.html.erb
<h2>New Album</h2>

<form action="/albums" method="post" accept-charset="utf-8">
	<%= render "album_form" %>
	<input type="submit" value="create">
</form>

w4d4/musicapp/app/views/albums/show.html.erb
<%= render "layouts/header", obj: @album %>

<h2><%= @album.artist.name %> - <%= @album.name %></h2>
<%= link_to "edit", edit_album_url(@album) %>
<%= link_to "delete(!)", album_url(@album), method: :delete %>

<h3>Tracks</h3>
<ul>
	<% @album.tracks.each do |a| %>
		<li><%= link_to a.name, track_url(a) %></li>
	<% end %>
	<li style="list-style-type: none; text-indent: -1em;">
		<%= link_to "new", new_album_track_url(@album) %>
	</li>
</ul>