w4d4/musicapp/config/routes.rb
Rails.application.routes.draw do
  get 'artists/index'

  root to: "artists#index"
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :artists do 
    resources :albums, only: :new
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end
  resources :tracks, except: [:index, :new] do
    resources :notes, only: :create
  end
  resource :notes, only: :destroy
end

w4d4/musicapp/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ActiveRecord::Base
  has_many :albums, dependent: :destroy
end

w4d4/musicapp/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :redirect_unless_logged_in, except: :index

  def index
    if logged_in?
      @artists = Artist.all
      render :index
    else
      @user = User.new
      render "sessions/new"
    end
  end

  def show
    find_artist!
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      inform("artist \"#{@artist.name}\" created")
      redirect_to artists_url
    else
      render :new
    end
  end

  def edit
    find_artist!
  end

  def update
    find_artist!
    if @artist.update(artist_params)
      inform("artist \"#{@artist.name}\" updated")
      redirect_to artist_url(@artist)
    else
      flash.now[:errors] = @artist.errors.full_messages
      render :edit
    end
  end

  def destroy
    find_artist!
    inform("artist \"#{@artist.name}\" deleted")
    @artist.destroy
    redirect_to artists_url
  end

  private

  def artist_params
    params.require(:artist).permit(:name)
  end

  def find_artist!
    @artist = Artist.find(params[:id])
  end
end

w4d4/musicapp/app/helpers/artists_helper.rb
module ArtistsHelper
end

w4d4/musicapp/app/views/artists/edit.html.erb
<h2>Edit Artist</h2>

<form action="<%= artist_url(@artist) %>" method="post" accept-charset="utf-8">
	<input type="hidden" name="_method" value="patch">
	<input type="hidden" name="authenticity_token"
		value="<%= form_authenticity_token %>">
	<label for="name">Name:</label>
	<input type="text" name="artist[name]" value="<%= @artist.name %>" id="name">

	<input type="submit" value="edit">
	<%= link_to "cancel", artist_url(@artist) %>
</form>

w4d4/musicapp/app/views/artists/index.html.erb
c'est ne pas l'indice des artistes

<h2>Artists</h2>
<ul>
	<% @artists.each do |a| %>
		<li>
			<%= link_to a.name, artist_url(a) %>
			<%= link_to "edit", edit_album_url(a) %>
			<%= link_to "delete(!)", album_url(a), method: :delete %>
		</li>
	<% end %>
	<li style="list-style-type: none; text-indent: -1em;">
		<%= link_to "new artist", new_artist_url %>
	</li>
</ul>

w4d4/musicapp/app/views/artists/new.html.erb
<h2>New Artist</h2>

<form action="/artists" method="post" accept-charset="utf-8">
	<input type="hidden" name="authenticity_token"
		value="<%= form_authenticity_token %>">
	<label for="name">Name:</label>
	<input type="text" name="artist[name]" value="" id="name">

	<input type="submit" value="create">
	<%= link_to "cancel", artists_url %>
</form>

w4d4/musicapp/app/views/artists/show.html.erb
<%= render "layouts/header", obj: @artist %>

<h2><%= @artist.name %></h2>
<%= link_to "edit", edit_artist_url(@artist) %>
<%= link_to "delete(!)", artist_url(@artist), method: :delete %>

<h3>Albums</h3>
<ul>
	<% @artist.albums.each do |a| %>
		<li>
			<%= link_to a.name, album_url(a) %>
			<%= link_to "edit", edit_album_url(a) %>
			<%= link_to "delete(!)", album_url(a), method: :delete %>
		</li>
	<% end %>
	<li style="list-style-type: none; text-indent: -1em;">
		<%= link_to "new", new_artist_album_url(@artist) %>
	</li>
</ul>